### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by jleclanche** [uranusjr/pystandardpaths#1]
I'm currently looking at bringing both a js and a python implementation of QtStandardPaths under a single umbrella to ease cross-platform projects transitioning to xdg-basedir style config.

I see this project is no longer maintained but it's essentially what I'm looking for. Would you be willing to transfer its maintenance to me?

**Comment by uranusjr** [comment]
This project is not unmaintained. I use it for my daytime job, and have deployed it to quite a lot embedded devices running in the wild. I don’t use all the features myself, but I haven’t found any bugs for a long time now. Just send a pull request if you run into any problems, and I’ll release asap. :)

**Comment by jleclanche** [comment]
Oh that's great to hear!
